fix nokogiri & mdbook installs (#62)
* upgrade nokogiri

we're running into the issue fixed in https://github.com/sparklemotion/nokogiri/pull/2106

* build mdbook without search feature

error is:

error: failed to compile `mdbook v0.2.3`, intermediate artifacts can be found at `/tmp/cargo-installjZOKMC`

Caused by:
  failed to select a version for the requirement `ammonia = "^1.1"`
  candidate versions found which didn't match: 3.3.0, 3.2.1, 3.2.0, ...

I believe because ammonia-1.1 was pulled from crates.io